services:
  - type: web
    name: prontivus-backend-2 # This MUST match your Render web service name
    env: python
    plan: free
    # Since your backend files are at the root of the repository,
    # you do not need to specify a 'rootDir' here.
    buildCommand: bash -c "poetry install --only main --no-root && pip install psutil && pip install PyJWT"
    startCommand: poetry run uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8  # This will explicitly tell Render to use Python 3.11.8
      # Database Connection Details (from your Render PostgreSQL instance)
      - key: DATABASE_URL
        value: postgresql://prontivus_db_xq59_user:8Sieb85fpppbfbcmGa7IPri01BDywGAfL@prontivus-db.internal:5432/prontivus_db_xq59
      - key: DATABASE_URL_ASYNC
        value: postgresql+asyncpg://prontivus_db_xq59_user:8Sieb85fpppbfbcmGa7IPri01BDywGAfL@prontivus-db.internal:5432/prontivus_db_xq59
      - key: POSTGRES_USER
        value: prontivus_db_xq59_user
      - key: POSTGRES_PASSWORD
        value: 8Sieb85fpppbfbcmGa7IPri01BDywGAfL
      - key: POSTGRES_HOST
        value: prontivus-db.internal
      - key: POSTGRES_PORT
        value: 5432
      - key: POSTGRES_DB
        value: prontivus_db_xq59
      # Application Settings
      - key: USE_DATABASE
        value: "true"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false" 